name: EKS Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'deployment/eks-terraform/**'
  workflow_dispatch: {}
jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: deployment/eks-terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ap-south-1 \
            --name demo-eks

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Install ArgoCD
        run: |
          # kubectl create namespace argocd || true

          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

          helm upgrade --install argocd argo/argo-cd \
            --namespace argocd \
            --create-namespace \
            --set server.service.type=LoadBalancer

      - name: Get ArgoCD Initial Admin Password
        run: |
          kubectl get secret argocd-initial-admin-secret \
            -n argocd \
            -o jsonpath="{.data.password}" | base64 -d

      - name: Install Traefik
        run: |
          # kubectl create namespace traefik || true

          helm repo add traefik https://traefik.github.io/charts
          helm repo update

          helm upgrade --install traefik traefik/traefik \
            --namespace traefik \
            --create-namespace \
            --set service.type=LoadBalancer

      - name: Get Services
        run: kubectl get svc -A


  # aws eks update-kubeconfig --region ap-south-1 --name demo-eks
  # kubectl get nodes